@host = http://localhost:5000

# ================================
# UserService CRUD through API Gateway
# ================================

### Get all users
GET {{host}}/users
Accept: application/json


### Get a single user by ID
GET {{host}}/users/1
Accept: application/json


### Create a new user
POST {{host}}/users
Content-Type: application/json

{
  "name": "Alice Johnson"
}


### Update a user by ID
PUT {{host}}/users/1
Content-Type: application/json

{
  "name": "Updated Alice Johnson"
}


### Delete a user by ID
DELETE {{host}}/users/1



# ================================
# OrderService CRUD through API Gateway
# ================================

### Get all orders
GET {{host}}/orders
Accept: application/json


### Get a single order by ID
GET {{host}}/orders/1
Accept: application/json


### Create a new order
POST {{host}}/orders
Content-Type: application/json

{
  "userId": 1,
  "product": "Smartphone",
  "quantity": 2
}


### Update an order by ID
PUT {{host}}/orders/1
Content-Type: application/json

{
  "product": "Updated Smartphone",
  "quantity": 5
}


### Delete an order by ID
DELETE {{host}}/orders/1
